### ISSUE TITLE
System.Threading.Threadの参照をTask変更できませんか？

### ISSUE THREAD

**Issue by NewBLife** [ume05rw/SharpCifs.Std#1]
UWPアプリも使いたいです、でもUWPにSystem.Threading.Threadの参照ができないですよ。
System.Threading.ThreadをTask変更できませんか？

**Comment by ume05rw** [comment]
thanks for your contact.
In China, programming is so active. I am envious a little.

I have never touched UWP, so I don't know the details.
but Currently, this code has issues related to System.Threading.Thread.(ex: Thread.Abort(); not implement)

I ｔｒｙ to deal with this problem, when spare time, and intarested.
However, I'm not planning to deal with this problem in a hurry.

If you deal with it, I will discard my code and switch to yours! :-)

**Comment by NewBLife** [comment]
Thank you ! 
I have solved the problem. I use TPL replaced the Thread pacage. @ume05rw

**Comment by NewBLife** [comment]
I am in Japan now and develop uwp or xamarin applications in japanese company.

**Comment by ume05rw** [comment]
hi!

fixed this problem which was pending.
(but, It seems that you solved it sooner...^^;)

Anyway, thank you for letting me know the problem.

Enjoying GW!
