### ISSUE TITLE
Strong naming

### ISSUE THREAD

**Issue by Kaon68** [ume05rw/SharpCifs.Std#11]
Hi

Could you sign / add strong name to your assembly so it can be referenced by strong named assemblies ?

Thx :)

**Comment by ume05rw** [comment]
Hi, thanks for your message!

hmm, When saying Strong-Named Assembly, is it related to the Key file which is often seen in MS source code etc?
I don't know well about the convenience of signing. It's a good opportunity, so I'll give it a try.

Wait a moment!

**Comment by ume05rw** [comment]
I published a new NuGet package, ver 0.2.11.
The dll in the package is signed, and has a strong name.

I am glad if you try it!

**Comment by Kaon68** [comment]
ok, thanks for acting so fast :)

I'll try it as soon as possible and give you feedback.

**Comment by Kaon68** [comment]
ok, it's working.

Thx again for your reactivity.

**Comment by ume05rw** [comment]
Thanks for your feedback!
