### ISSUE TITLE
Question: GetCanonicalPath

### ISSUE THREAD

**Issue by LukePulverenti** [ume05rw/SharpCifs.Std#3]
What is the intention here:

https://github.com/ume05rw/SharpCifs.Std/blob/4dd5989b980735b3f0279a5f85f0d626cfd10b19/SharpCifs.STD1.3/Util/Sharpen/FilePath.cs#L131

**Comment by LukePulverenti** [comment]
Is this a typo, because the results of TrimEnd are not actually being utilized. Thanks !

**Comment by ume05rw** [comment]
Thanks for your notice!

It was already written like this when I cloned.

I'll check up what they wanted to do...

**Comment by ume05rw** [comment]
hi!

removed the line that you pointed out.

it seems, tried to mimic the trailing space deletion that the original-jcifs was processing.

System.IO.Path.GetFullPath processed it first,
so Nobody was aware of this.

Thanks!
