### ISSUE TITLE
连接Cifs服务器的时候，报错Failed to connect: 0.0.0.0<00>/192.168.1.27

### ISSUE THREAD

**Issue by hyy829119** [ume05rw/SharpCifs.Std#8]
I use the demo on the website and then the direct link appears to be so wrong, the reason why this error is possible??

at SharpCifs.Smb.SmbTransport.Connect()
   at SharpCifs.Smb.SmbTree.TreeConnect(ServerMessageBlock andx, ServerMessageBlock andxResponse)
   at SharpCifs.Smb.SmbFile.DoConnect()
   at SharpCifs.Smb.SmbFile.Connect()
   at SharpCifs.Smb.SmbFile.Connect0()
   at SharpCifs.Smb.SmbFile.QueryPath(String path, Int32 infoLevel)
   at SharpCifs.Smb.SmbFile.Exists()
   at DsSmartCloud.OssDao.CifsGlusterfsRepositily.PushStreamToGlusterFs(String appid, Byte[] stream, String uploadid, String name, Int64 totalsize) in E:\BjXinzheProj\SmartCloudGateWay\SmartCloudGateWay\GlusterFs\CifsGlusterfsRepositily.cs:line 80

**Comment by ume05rw** [comment]
aa..., I got crazy and furious about this problem many time.

It look like name resolution failure.
If you using the Host Name String for the server address, change it to IP address.
If it seems to be successful, it is a matter of name resolution.

here a name resolution sample:  
[http://sharpcifsstd.dobes.jp/#howtouse_name](http://sharpcifsstd.dobes.jp/#howtouse_name)

    try
    {
        SharpCifs.Config.SetProperty("jcifs.smb.client.lport", "8137"); //udp broadcast client(myself) port.
        var naddr = NbtAddress.GetByName("HostName");
    }
    catch(Exception)
    {
        //cannot resolve.
    }

If this answer is misplaced, please let me know your development environment in detail(platform, os, smb-servers...).

**Comment by NewBLife** [comment]
检查一下共享设置，SMB链接地址，以及System.Thread的版本。 @hyy829119

**Comment by ume05rw** [comment]
I remembered it now!

try to set this param:
SharpCifs.Config.SetProperty("jcifs.smb.client.laddr", "your IP ADDRESS");

In some cases, it was not possible to acquire the local address.
This is because the acquired host name may be in an incorrect format as the DNS name (eg, it contains spaces).

I experienced it with an iOS device, and It may also occur with other devices.

**Comment by hyy829119** [comment]
Heartfelt thanks to
The reason for the problem is that you really need to set the IP property,
Try to set this param:
The sharpcies.config.config.setproperty (" jcifs.smb.client.laddr ", "your IP ADDRESS");
This solves my problem

**Comment by ume05rw** [comment]
That's good!

**Comment by hyy829119** [comment]
Hi.
I want to ask again,
SharpCifs.Smb 
Is there a way to directly receive the file stream?

**Comment by ume05rw** [comment]
Hi!

No, It is impossible to get a castable Stream in System.IO.FileStream.
You can tell if you read Smb/SmbTransport.cs, Util/Transport/Transport.cs, The actual process of Stream exchanges byte[] which cutted out a part of a file every time of query, on a Socket.

By the way, why do you want to use FileStream?

**Comment by ume05rw** [comment]
Hi  hyy829119, was it possible to convert Stream?
I hope that it works well.

Since there is no particular progress, I will close this issue.
If there is something, please give me feedbacks again!
